from storescraper.categories import CELL, NOTEBOOK, STEREO_SYSTEM, KEYBOARD, \
    MOUSE, CELL_ACCESORY, WEARABLE, TABLET, REFRIGERATOR, HEADPHONES, CAMERA, \
    KEYBOARD_MOUSE_COMBO, VIDEO_GAME_CONSOLE, MONITOR, PROJECTOR, MEMORY_CARD, \
    GAMING_CHAIR, STORAGE_DRIVE, POWER_SUPPLY, COMPUTER_CASE, USB_FLASH_DRIVE, \
    RAM, TELEVISION, AIR_CONDITIONER, OVEN, WASHING_MACHINE, LAMP, UPS, \
    ALL_IN_ONE, VIDEO_CAMERA, STOVE, PROCESSOR, VACUUM_CLEANER, DISH_WASHER, \
    PRINTER, VIDEO_GAME

ml_to_cateogry = {
    "Celulares y Telefonía": CELL,
    "Computación": NOTEBOOK,
    "Electrónica, Audio y Video": STEREO_SYSTEM,
    "Hogar y Muebles": None,
    "Audio": STEREO_SYSTEM,
    "Cables": None,
    "Controles Remotos": None,
    "Cables y Hubs USB": None,
    "Notebooks y Accesorios": NOTEBOOK,
    "Periféricos de PC": KEYBOARD,
    "Tablets y Accesorios": TABLET,
    "Lápices Touch": None,
    "Teclados": KEYBOARD,
    "Mouses": MOUSE,
    "Trackpads": None,
    "Cables y Adaptadores": None,
    "Candados de Seguridad": None,
    "Accesorios para Celulares": CELL_ACCESORY,
    "Smartwatches y Accesorios": WEARABLE,
    "Cargadores": None,
    "Mallas": None,
    "Adaptadores": None,
    "Cables de Datos": None,
    "Carcasas, Fundas y Protectores": None,
    "Otros": None,
    "Cargadores con Cable": None,
    "Inalambrico": None,
    "Para TV": None,
    "Smartwatches": WEARABLE,
    "Accesorios": None,
    "Tablets": TABLET,
    "PC de Escritorio": None,
    "Accesorios para Audio y Video": None,
    "Netbooks": NOTEBOOK,
    "Notebooks": NOTEBOOK,
    "Celulares y Smartphones": CELL,
    "Electrodomésticos": REFRIGERATOR,
    "Vestuario y Calzado": None,
    "Audio Portátil y Accesorios": STEREO_SYSTEM,
    "Audífonos": HEADPHONES,
    "Artefactos de Cuidado Personal": None,
    "Pequeños Electrodomésticos": OVEN,
    "Cámaras Web": CAMERA,
    "Mouses y Teclados": KEYBOARD_MOUSE_COMBO,
    "Telefonía Fija e Inalámbrica": None,
    "Colgantes y Soportes": None,
    "Apoya Celulares": CELL_ACCESORY,
    "Porta Celulares": CELL_ACCESORY,
    "Portatiles": NOTEBOOK,
    "Carcasas y Fundas": CELL_ACCESORY,
    "Cases": CELL_ACCESORY,
    "Láminas Protectoras": CELL_ACCESORY,
    "Consolas y Videojuegos": VIDEO_GAME_CONSOLE,
    "Construcción": None,
    "Juegos y Juguetes": None,
    "Iluminación para el Hogar": None,
    "Seguridad para el Hogar": None,
    "Alarmas y Sensores": None,
    "Circuito de Cámaras": None,
    "Cámaras de Vigilancia": None,
    "Accesorios para Consolas": None,
    "Accesorios para PC Gaming": None,
    "Xbox Series X/S": VIDEO_GAME_CONSOLE,
    "Otros Xboxs": None,
    "Monitores y Accesorios": MONITOR,
    "Kits de Mouse y Teclado": KEYBOARD_MOUSE_COMBO,
    "Accesorios para Vehículos": None,
    "Animales y Mascotas": None,
    "Arte, Librería y Cordonería": None,
    "Bebés": None,
    "Belleza y Cuidado Personal": None,
    "Cámaras y Accesorios": CAMERA,
    "Deportes y Fitness": None,
    "Libros, Revistas y Comics": None,
    "Relojes y Joyas": None,
    "Salud y Equipamiento Médico": None,
    "Pesas de Baño": None,
    "Termómetros": None,
    "Relojes Murales": None,
    "Adornos y Decoración del Hogar": None,
    "Cocina y Menaje": None,
    "Muebles para el Hogar": None,
    "Textiles de Hogar y Decoración": None,
    "Porteros Eléctricos": None,
    "Ampolletas": None,
    "Cintas LED": None,
    "Accesorios para TV": None,
    "Componentes Electrónicos": None,
    "Media Streaming": None,
    "Proyectores y Telones": PROJECTOR,
    "Asistentes Virtuales": None,
    "Equipos de DJ y Accesorios": None,
    "Micrófonos y Preamplificadores": None,
    "Camping, Caza y Pesca": None,
    "Monopatines y Scooters": None,
    "Accesorios para Cámaras": None,
    "Filmadoras y Cámaras de Acción": None,
    "Estudio e Iluminación": None,
    "Para Cámaras de Acción": None,
    "Tarjetas de Memoria y Lectores": MEMORY_CARD,
    "Controles para Gamers": None,
    "Sillas Gamer": GAMING_CHAIR,
    "Para PlayStation": None,
    "Para Xbox": None,
    "PS4 - PlayStation 4": VIDEO_GAME_CONSOLE,
    "PS5 - PlayStation 5": VIDEO_GAME_CONSOLE,
    "Almacenamiento": STORAGE_DRIVE,
    "Componentes de PC": None,
    "Conectividad y Redes": None,
    "Software": None,
    "Estuches y Fundas": None,
    "Parlantes para PC": STEREO_SYSTEM,
    "Mouse Pads": None,
    "Tabletas Digitalizadoras": TABLET,
    "Accesorios para Notebooks": None,
    "Bases Enfriadoras": None,
    "Cargadores y Fuentes": None,
    "Fundas": None,
    "Hubs USB": None,
    "Mochilas, Maletines y Fundas": None,
    "Bases": None,
    "Monitores": MONITOR,
    "Adaptadores USB": None,
    "Cables de Red y Accesorios": None,
    "Routers": None,
    "Coolers y Ventiladores": None,
    "Discos y Accesorios": None,
    "Fuentes de Alimentación": POWER_SUPPLY,
    "Gabinetes y Soportes de PC": COMPUTER_CASE,
    "Cables de Audio y Video": None,
    "Pen Drives": USB_FLASH_DRIVE,
    "Joysticks": None,
    "Memorias": RAM,
    "Soportes para Vehiculos": None,
    "Fundas Cargadoras": CELL_ACCESORY,
    "Artículos de Bebé para Baños": None,
    "Juegos y Juguetes para Bebés": None,
    "Accesorios de Auto y Camioneta": None,
    "Audio para Vehículos": None,
    "Handies y Radiofrecuencia": None,
    "Manos Libres": None,
    "Televisores": TELEVISION,
    "Home Theater": STEREO_SYSTEM,
    "Parlantes y Subwoofers": STEREO_SYSTEM,
    "Climatización": AIR_CONDITIONER,
    "Hornos y Cocinas": OVEN,
    "Lavado": WASHING_MACHINE,
    "Refrigeración": REFRIGERATOR,
    "Refrigeradores": REFRIGERATOR,
    "Repuestos y Accesorios": None,
    "Aspiradoras": VACUUM_CLEANER,
    "Aspiradoras Robot": VACUUM_CLEANER,
    "Lavadora-Secadoras": WASHING_MACHINE,
    "Lavavajillas": DISH_WASHER,
    "Secadoras": WASHING_MACHINE,
    "Aires Acondicionados": AIR_CONDITIONER,
    "Lápices y Uñetas": None,
    "Herramientas": None,
    "Industrias y Oficinas": None,
    "Otras Categorías": None,
    "Equipaje y Accesorios de Viaje": None,
    "Mochilas": None,
    "Tratamientos Respiratorios": None,
    "Humidificadores": None,
    "Purificadores de Aire": None,
    "Lámparas": LAMP,
    "Para Cocina": None,
    "Para Hogar": None,
    "Artefactos para el Cabello": None,
    "Balanzas de Baño": None,
    "Ciclismo": None,
    "Pulsómetros y Cronómetros": None,
    "Monociclos Eléctricos": None,
    "Monopatines": None,
    "De Pie": None,
    "Eléctricos": None,
    "Cámaras": CAMERA,
    "Revelado y Laboratorio": None,
    "Antenas Wireless": None,
    "Parlantes": STEREO_SYSTEM,
    "Barbería": None,
    "Cuidado de la Piel": None,
    "Higiene Personal": None,
    "Cepillos": None,
    "Cepillos Eléctricos": None,
    "UPS": UPS,
    "Ultrabooks": NOTEBOOK,
    "Switches": None,
    "Memorias RAM": RAM,
    "Tarjetas de Red": None,
    "Impresión": PRINTER,
    "Impresoras": PRINTER,
    "Insumos de Impresión": None,
    "Cartuchos de Tinta": None,
    "Tintas": None,
    "Toners": None,
    "Repuestos": None,
    "Micrófonos": None,
    "Para Nintendo": None,
    "Headsets": HEADPHONES,
    "Docking Stations": None,
    "Maletines y Bolsos": None,
    "Filtros de Privacidad": None,
    "Soportes": None,
    "Memorias Digitales": None,
    "All In One": ALL_IN_ONE,
    "Computadores": None,
    "Mini PCs": None,
    "Repuestos para Notebooks": None,
    "Micro y Minicomponentes": STEREO_SYSTEM,
    "Consolas": VIDEO_GAME_CONSOLE,
    "Fundas y Estuches": None,
    "Audio y Video para Gaming": None,
    "Fundas para Controles": None,
    "Discos Duros y SSDs": STORAGE_DRIVE,
    "Sillas": GAMING_CHAIR,
    "Sillas Tándem": GAMING_CHAIR,
    "Otros Cables": None,
    "Soportes para Parlantes": None,
    "Baterías": None,
    "Videojuegos": VIDEO_GAME,
    "Antigüedades y Colecciones": None,
    "Lentes y Accesorios": None,
    "Llaveros": None,
    "Paraguas": None,
    "Lentes de Sol": None,
    "Ópticos": None,
    "Juegos de Agua y Playa": None,
    "Juegos de Construcción": None,
    "Juegos de Mesa y Cartas": None,
    "Juegos de Salón": None,
    "Juguetes Antiestrés e Ingenio": None,
    "Juguetes de Oficios": None,
    "Muñecos y Muñecas": None,
    "Peluches": None,
    "Figuras de Acción": None,
    "Muñecas y Bebés": None,
    "Puzzles": None,
    "Trompos": None,
    "Cartas Coleccionables R.P.G.": None,
    "Juegos de Mesa": None,
    "Pilas y Cargadores": None,
    "Video": VIDEO_CAMERA,
    "Cargadores de Pilas": None,
    "Pilas": None,
    "Amplificadores y Receivers": None,
    "Pinballs y Arcade": None,
    "PS2 - PlayStation 2": VIDEO_GAME_CONSOLE,
    "PS3 - PlayStation 3": VIDEO_GAME_CONSOLE,
    "Cargadores para Controles": None,
    "Gamepads y Joysticks": None,
    "Controles": None,
    "Skins": None,
    "Controles y Joysticks": None,
    "Game Boy Advance - GBA": VIDEO_GAME_CONSOLE,
    "Game Cube": VIDEO_GAME_CONSOLE,
    "Nintendo Switch": VIDEO_GAME_CONSOLE,
    "Nintendo Wii": VIDEO_GAME_CONSOLE,
    "Nintendo Wii U": VIDEO_GAME_CONSOLE,
    "Protectores de Pantalla": CELL_ACCESORY,
    "Cables de Red": None,
    "Cuadernos": None,
    "Estuches de Lápices": None,
    "Enfriadores de Aire": None,
    "Estufas y Calefactores": STOVE,
    "Ventiladores": None,
    "Planchas": None,
    "Hervidores": None,
    "Preparación de Alimentos": None,
    "Preparación de Bebidas": None,
    "Arroceras": None,
    "Batidoras": None,
    "Sartenes y Ollas Eléctricas": None,
    "Tostadoras": None,
    "Cocinas": STOVE,
    "Extractores y Purificadores": None,
    "Hornos": OVEN,
    "Artículos de Vino y Coctelería": None,
    "Cocción y Horneado": OVEN,
    "Utensilios de Preparación": None,
    "Vajilla y Artículos de Servir": None,
    "Bandejas": None,
    "Cuchillería": None,
    "Cuchillos de Cocina": None,
    "Juegos de Cuchillería": None,
    "Coladores y Tendederos": None,
    "Medidores de Cocina": None,
    "Baterías de Cocina": None,
    "Ollas": None,
    "Sartenes": None,
    "Balanzas de Cocina": None,
    "Máquinas para Postres": None,
    "Licuadoras": None,
    "Cafeteras": None,
    "Encimeras": None,
    "Calefonts y Termos": None,
    "Sistemas de Monitoreo": None,
    "Timbres": None,
    "Dispensadores y Purificadores": None,
    "Filtros": None,
    "Jardín y Aire Libre": None,
    "Freidoras": None,
    "Hornos de Pan": None,
    "Microondas": OVEN,
    "Cavas de Vino": None,
    "Freezers": REFRIGERATOR,
    "Almacenamiento y Organización": None,
    "Vajilla": None,
    "Fuentes": None,
    "Jarras": None,
    "Juegos de Vajilla": None,
    "Afiladores": None,
    "Moldes": None,
    "Tablas para Picar": None,
    "Bandejas, Asaderas y Fuentes": None,
    "Baterías, Ollas y Sartenes": None,
    "Vaporieras": None,
    "Para Cocinas y Hornos": None,
    "Calderas": None,
    "Chimeneas y Salamandras": None,
    "Calefonts": None,
    "Termos": None,
    "Baños": None,
    "Piscinas y Accesorios": None,
    "Spa Exterior": None,
    "Calentadores": None,
    "Limpieza y Mantenimiento": None,
    "Piscinas": None,
    "Accesorios para Baño": None,
    "Tinas": None,
    "Electricidad": None,
    "Mobiliario para Baños": None,
    "Jugueras": None,
    "Minipimers": None,
    "Parrillas Eléctricas": None,
    "Sandwicheras": None,
    "Procesadores": PROCESSOR,
    "Waffleras": None,
    "Yogurteras": None,
    "Utensilios de Repostería": None,
    "Tenedores": None,
    "Para Aires Acondicionados": AIR_CONDITIONER,
    "Para Calefont y Termos": None,
    "Gasfitería": None,
    "Mobiliario para Cocinas": None,
    "Exprimidores Eléctricos": None,
    "Mopas a Vapor": None
}
